name: freshguard
description: Premium Eco Food Waste and Spoilage Predictor Application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  google_generative_ai: ^0.4.0
  flutter_barcode_scanner: ^2.0.0
  google_mlkit_text_recognition: ^0.11.0
  intl: ^0.20.2
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
