// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANE_DLPenFMoCt3Owj4NF9h4GRV43mhfg',
    appId: '1:334480616493:web:fad1a113667b2ab9485ca4',
    messagingSenderId: '334480616493',
    projectId: 'freshguard-8a14f',
    authDomain: 'freshguard-8a14f.firebaseapp.com',
    storageBucket: 'freshguard-8a14f.firebasestorage.app',
    measurementId: 'G-W135XXR8KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfqB754j6t6etsHCknGQA6yLXW77-8Mg',
    appId: '1:334480616493:android:a5c54c25843b49ff485ca4',
    messagingSenderId: '334480616493',
    projectId: 'freshguard-8a14f',
    storageBucket: 'freshguard-8a14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7e6z4XWOQ5F0Uw0_3XnTaz0MHRAn9qkk',
    appId: '1:334480616493:ios:54bb002413852278485ca4',
    messagingSenderId: '334480616493',
    projectId: 'freshguard-8a14f',
    storageBucket: 'freshguard-8a14f.firebasestorage.app',
    iosClientId: '334480616493-mv0sj29g31g9i4r7scepkhvu52rq7n88.apps.googleusercontent.com',
    iosBundleId: 'com.freshguard.freshguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7e6z4XWOQ5F0Uw0_3XnTaz0MHRAn9qkk',
    appId: '1:334480616493:ios:54bb002413852278485ca4',
    messagingSenderId: '334480616493',
    projectId: 'freshguard-8a14f',
    storageBucket: 'freshguard-8a14f.firebasestorage.app',
    iosClientId: '334480616493-mv0sj29g31g9i4r7scepkhvu52rq7n88.apps.googleusercontent.com',
    iosBundleId: 'com.freshguard.freshguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANE_DLPenFMoCt3Owj4NF9h4GRV43mhfg',
    appId: '1:334480616493:web:b6cc22c04433373e485ca4',
    messagingSenderId: '334480616493',
    projectId: 'freshguard-8a14f',
    authDomain: 'freshguard-8a14f.firebaseapp.com',
    storageBucket: 'freshguard-8a14f.firebasestorage.app',
    measurementId: 'G-GCMRZR56QS',
  );
}
